import type { EventData, Category } from "./types";

export const mockEvents: EventData[] = [
  {
    id: "1",
    tenantId: "t1",
    title: "Live Jazz Avond",
    subtitle: "Met het Amsterdam Jazz Quartet",
    shortDescription: "Geniet van een onvergetelijke avond live jazz in ons sfeervolle café.",
    fullDescription: "Een avond vol swingende jazz classics en moderne improvisatie.",
    category: "live-muziek",
    startDate: "2026-04-18",
    startTime: "20:00",
    endTime: "23:30",
    venue: "Café De Kroeg",
    address: "Kerkstraat 12, Amsterdam",
    organizer: "Café De Kroeg",
    featuredImage: "",
    status: "published",
    slug: "live-jazz-avond",
    tags: ["jazz", "live muziek", "amsterdam"],
    ctaButtonText: "Reserveer nu",
    ctaLink: "#",
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "2",
    tenantId: "t1",
    title: "Wijnproeverij Italië",
    subtitle: "Ontdek de beste Italiaanse wijnen",
    shortDescription: "Proef 8 exclusieve Italiaanse wijnen met deskundig commentaar.",
    category: "proeverij",
    startDate: "2026-04-25",
    startTime: "19:00",
    endTime: "21:30",
    venue: "Café De Kroeg",
    address: "Kerkstraat 12, Amsterdam",
    organizer: "Café De Kroeg",
    status: "draft",
    slug: "wijnproeverij-italie",
    tags: ["wijn", "proeverij"],
    createdAt: "2026-04-02T10:00:00Z",
    updatedAt: "2026-04-02T10:00:00Z",
  },
  {
    id: "3",
    tenantId: "t1",
    title: "Pub Quiz Avond",
    subtitle: "Test je kennis!",
    shortDescription: "Elke donderdag een spannende pub quiz.",
    category: "thema-avond",
    startDate: "2026-04-17",
    startTime: "20:30",
    endTime: "22:30",
    venue: "Café De Kroeg",
    address: "Kerkstraat 12, Amsterdam",
    organizer: "Café De Kroeg",
    status: "published",
    slug: "pub-quiz-avond",
    isRecurring: true,
    recurringPattern: "weekly",
    tags: ["quiz", "wekelijks"],
    createdAt: "2026-04-01T08:00:00Z",
    updatedAt: "2026-04-01T08:00:00Z",
  },
  {
    id: "4",
    tenantId: "t1",
    title: "Beach Volleyball Toernooi",
    subtitle: "Zomer editie 2026",
    shortDescription: "Schrijf je team in voor het jaarlijkse beachvolleybal toernooi.",
    category: "sport",
    startDate: "2026-05-10",
    endDate: "2026-05-10",
    startTime: "10:00",
    endTime: "18:00",
    venue: "Beachclub Zandzee",
    address: "Strandweg 45, Scheveningen",
    organizer: "Beachclub Zandzee",
    status: "scheduled",
    slug: "beach-volleyball-toernooi",
    publishAt: "2026-04-15T09:00:00Z",
    tags: ["sport", "volleyball", "strand"],
    createdAt: "2026-04-03T10:00:00Z",
    updatedAt: "2026-04-03T10:00:00Z",
  },
];

export const defaultCategories: Category[] = [
  { id: "c1", name: "Sport", slug: "sport", color: "#3B82F6", isDefault: true },
  { id: "c2", name: "Proeverij", slug: "proeverij", color: "#8B5CF6", isDefault: true },
  { id: "c3", name: "Live Muziek", slug: "live-muziek", color: "#EC4899", isDefault: true },
  { id: "c4", name: "Thema Avond", slug: "thema-avond", color: "#F59E0B", isDefault: true },
  { id: "c5", name: "Overig", slug: "overig", color: "#6B7280", isDefault: true },
];
